---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: honeycomb
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels: 
    istio-injection: "enabled"
    needs-private-registry-creds: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels: 
    istio-injection: "enabled"
    needs-private-registry-creds: "true"
