apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dev-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "api.dev.{{ENVIRONMENT}}.twdps.io"
      tls:
        httpsRedirect: true # sends 301 redirect for http requests  
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - api.dev.{{ENVIRONMENT}}.twdps.io
